### ISSUE TITLE
Credentials best-practices

### ISSUE THREAD

**Issue by vbudilov** [EddyVerbruggen/nativescript-aws#1]
You wouldn't want to include your access tokens in the code -- the best practice is to use Cognito or WIF (preferably Cognito) to get temporary credentials. Hard-coding credentials is a huge security risk. 

```
AWS.config.update({
  region: AWS_region,
  **credentials: new Credentials(AWS_accessKeyId, AWS_secretAccessKey)**
});
```

**Comment by EddyVerbruggen** [comment]
It's best to grab them from a secured server or have the user supply them and store them securely. Or use Cognito indeed. Not sure how that affects this plugin though.
