### ISSUE TITLE
Get errors about missing 'Buffer'

### ISSUE THREAD

**Issue by naren8642** [EddyVerbruggen/nativescript-aws#3]
I installed the nativescript-aws plugin into my NativeScript project as per the documentation. And when I say: tns run android I get the following

node_modules/nativescript-aws/node_modules/aws-sdk/clients/acm.d.ts(108,37): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/acm.d.ts(110,38): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/acm.d.ts(344,32): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/apigateway.d.ts(991,23): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/clouddirectory.d.ts(841,38): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/cloudsearchdomain.d.ts(41,23): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/cloudtrail.d.ts(141,28): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/codecommit.d.ts(639,22): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/directconnect.d.ts(757,28): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/dms.d.ts(358,35): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/dynamodb.d.ts(293,38): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/dynamodbstreams.d.ts(92,38): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/ec2.d.ts(2651,23): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/ecr.d.ts(612,31): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/firehose.d.ts(144,22): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/glacier.d.ts(1116,24): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/iam.d.ts(1079,32): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/clients/iam.d.ts(2997,35): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/iotdata.d.ts(73,30): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/clients/iotdata.d.ts(74,25): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/clients/kinesis.d.ts(197,22): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/kms.d.ts(328,32): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/clients/kms.d.ts(957,31): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/lambda.d.ts(307,23): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/lambda.d.ts(308,28): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/polly.d.ts(69,29): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/rekognition.d.ts(438,27): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/s3.d.ts(746,22): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/clients/s3.d.ts(1050,42): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/s3.d.ts(3213,32): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/ses.d.ts(1127,32): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/sns.d.ts(275,24): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/sqs.d.ts(192,24): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/support.d.ts(336,22): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/waf.d.ts(372,39): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/clients/wafregional.d.ts(416,39): error TS2304: Cannot find name 'Buffer'.

node_modules/nativescript-aws/node_modules/aws-sdk/lib/config.d.ts(1,9): error TS2305: Module '"http"' has no exported member 'Agent'.
node_modules/nativescript-aws/node_modules/aws-sdk/lib/config.d.ts(2,35): error TS2307: Cannot find module 'https'.

node_modules/nativescript-aws/node_modules/aws-sdk/lib/dynamodb/document_client.d.ts(2,25): error TS2307: Cannot find module 'stream'.

node_modules/nativescript-aws/node_modules/aws-sdk/lib/dynamodb/document_client.d.ts(86,30): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/lib/dynamodb/document_client.d.ts(190,38): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/lib/http_response.d.ts(1,25): error TS2307: Cannot find module 'stream'.
node_modules/nativescript-aws/node_modules/aws-sdk/lib/http_response.d.ts(14,18): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/lib/request.d.ts(1,25): error TS2307: Cannot find module 'stream'.
node_modules/nativescript-aws/node_modules/aws-sdk/lib/request.d.ts(132,45): error TS2304: Cannot find name 'Buffer'.
node_modules/nativescript-aws/node_modules/aws-sdk/lib/services/glacier.d.ts(10,28): error TS2304: Cannot find name 'Buffer'.

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).....

**Comment by ghost** [comment]
I also getting these errors. Do you find any solution??

**Comment by naren8642** [comment]
No I didn't get any response... Now I actually switched over to React Native, so I am not even using NativeScript anymore...

**Comment by EddyVerbruggen** [comment]
Fair enough. Btw, this plugin was deprecated (see at the top of the readme) in favor of a different one.
