### ISSUE TITLE
Error while uploading data to AWS.S3

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/nativescript-aws#5]
import * as AWS from "nativescript-aws";

AWS.config.region = 'eu-west-1';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
IdentityPoolId: 'eu-west-1:d41172c5-0bb3-461e-9b6a-5bc9b445f970',
});

var bucket = new AWS.S3();

var userObj = {
userKey: "key",
email: "email",
}

var params = {
Bucket: 'dealerdb/',
Key: "profileDetails",
Body: JSON.stringify(userObj)
};

bucket.upload( params, function (err, result){
if (!err) {
console.log("page change");
} else {
console.log("error in page change",err);
}
});

I got error “NetworkingError: Missing credentials in config”

Any help please??

**Comment by EddyVerbruggen** [comment]
Missing credentials? Doesn't sound like a plugin issue really.. but you may want to switch to [this plugin](https://github.com/EddyVerbruggen/nativescript-nodeify#aws-sdk-or-amazon-cognito-identity-js-which-includes-aws-sdk) and try again..
